In [1]:
import pandas as pd

files = [
    "wc_traffic.csv",
    "ig_views.csv",
    "ig_interactions.csv",
    "ig_link clicks.csv",
    "ig_profile_visits.csv",
    "ig_follows.csv",
    "fb_views.csv",
    "fb_interactions.csv",
    "fb_link clicks.csv",
    "fb_visits.csv",
    "fb_follows.csv"
]

for file in files:
    print("\n" + "="*80)
    print(f"FILE: {file}")
    print("="*80)

    try:
        # Meta exports are usually UTF-16
        df = pd.read_csv(f"../Data/{file}", encoding="utf-16", skiprows=2)
    except:
        try:
            # Regular CSVs (GA4 traffic)
            df = pd.read_csv(f"../Data/{file}")
        except Exception as e:
            print("Error:", e)
            continue

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(list(df.columns))

    print("\nHead(5):")
    display(df.head())

================================================================================
FILE: wc_traffic.csv
================================================================================
Error: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2


================================================================================
FILE: ig_views.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00      229
1  2026-01-02T00:00:00       90
2  2026-01-03T00:00:00     1504
3  2026-01-04T00:00:00    19621
4  2026-01-05T00:00:00    16045

================================================================================
FILE: ig_interactions.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        6
1  2026-01-02T00:00:00        4
2  2026-01-03T00:00:00       81
3  2026-01-04T00:00:00       35
4  2026-01-05T00:00:00       40

================================================================================
FILE: ig_link clicks.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        0
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        3
3  2026-01-04T00:00:00       58
4  2026-01-05T00:00:00       59

================================================================================
FILE: ig_profile_visits.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        2
1  2026-01-02T00:00:00        3
2  2026-01-03T00:00:00       28
3  2026-01-04T00:00:00       75
4  2026-01-05T00:00:00       91

================================================================================
FILE: ig_follows.csv
================================================================================

Shape:
(55, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-03T00:00:00        6
1  2026-01-04T00:00:00       20
2  2026-01-05T00:00:00       13
3  2026-01-06T00:00:00        6
4  2026-01-07T00:00:00        9

================================================================================
FILE: fb_views.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00       67
1  2026-01-02T00:00:00       21
2  2026-01-03T00:00:00      828
3  2026-01-04T00:00:00    17687
4  2026-01-05T00:00:00    16281

================================================================================
FILE: fb_interactions.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00       10
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        8
3  2026-01-04T00:00:00        5
4  2026-01-05T00:00:00        0

================================================================================
FILE: fb_link clicks.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        2
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        0
3  2026-01-04T00:00:00        0
4  2026-01-05T00:00:00        0

================================================================================
FILE: fb_visits.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00       17
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        3
3  2026-01-04T00:00:00        6
4  2026-01-05T00:00:00       16

================================================================================
FILE: fb_follows.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        1
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        0
3  2026-01-04T00:00:00        0
4  2026-01-05T00:00:00        0

In [2]:
import pandas as pd

files = [
    "wc_traffic.csv",
    "ig_views.csv",
    "ig_interactions.csv",
    "ig_link clicks.csv",
    "ig_profile_visits.csv",
    "ig_follows.csv",
    "fb_views.csv",
    "fb_interactions.csv",
    "fb_link clicks.csv",
    "fb_visits.csv",
    "fb_follows.csv"
]

for file in files:
    print("\n" + "="*80)
    print(f"FILE: {file}")
    print("="*80)

    try:
        if file == "wc_traffic.csv":
            df = pd.read_csv(
                f"../Data/{file}",
                skiprows=8
            )
        else:
            df = pd.read_csv(
                f"../Data/{file}",
                encoding="utf-16",
                skiprows=2
            )

        print("\nShape:")
        print(df.shape)

        print("\nColumns:")
        print(list(df.columns))

        print("\nHead(5):")
        display(df.head())

    except Exception as e:
        print("Error:", e)

================================================================================
FILE: wc_traffic.csv
================================================================================

Shape:
(113, 2)

Columns:
['Nth day', 'Active users']

Head(5):

   Nth day  Active users
0       18             7
1       19             5
2       20             5
3       21             5
4       22            16

================================================================================
FILE: ig_views.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00      229
1  2026-01-02T00:00:00       90
2  2026-01-03T00:00:00     1504
3  2026-01-04T00:00:00    19621
4  2026-01-05T00:00:00    16045

================================================================================
FILE: ig_interactions.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        6
1  2026-01-02T00:00:00        4
2  2026-01-03T00:00:00       81
3  2026-01-04T00:00:00       35
4  2026-01-05T00:00:00       40

================================================================================
FILE: ig_link clicks.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        0
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        3
3  2026-01-04T00:00:00       58
4  2026-01-05T00:00:00       59

================================================================================
FILE: ig_profile_visits.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        2
1  2026-01-02T00:00:00        3
2  2026-01-03T00:00:00       28
3  2026-01-04T00:00:00       75
4  2026-01-05T00:00:00       91

================================================================================
FILE: ig_follows.csv
================================================================================

Shape:
(55, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-03T00:00:00        6
1  2026-01-04T00:00:00       20
2  2026-01-05T00:00:00       13
3  2026-01-06T00:00:00        6
4  2026-01-07T00:00:00        9

================================================================================
FILE: fb_views.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00       67
1  2026-01-02T00:00:00       21
2  2026-01-03T00:00:00      828
3  2026-01-04T00:00:00    17687
4  2026-01-05T00:00:00    16281

================================================================================
FILE: fb_interactions.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00       10
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        8
3  2026-01-04T00:00:00        5
4  2026-01-05T00:00:00        0

================================================================================
FILE: fb_link clicks.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        2
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        0
3  2026-01-04T00:00:00        0
4  2026-01-05T00:00:00        0

================================================================================
FILE: fb_visits.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00       17
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        3
3  2026-01-04T00:00:00        6
4  2026-01-05T00:00:00       16

================================================================================
FILE: fb_follows.csv
================================================================================

Shape:
(169, 2)

Columns:
['Date', 'Primary']

Head(5):

                  Date  Primary
0  2026-01-01T00:00:00        1
1  2026-01-02T00:00:00        0
2  2026-01-03T00:00:00        0
3  2026-01-04T00:00:00        0
4  2026-01-05T00:00:00        0

In [3]:
traffic = pd.read_csv("../Data/wc_traffic.csv", skiprows=8)

traffic["Date"] = pd.to_datetime("2026-01-01") + pd.to_timedelta(traffic["Nth day"] - 1, unit="D")

traffic = traffic.rename(columns={
    "Active users": "Active_Users"
})

traffic = traffic[["Date", "Active_Users"]]

display(traffic.head())
print(traffic.shape)

        Date  Active_Users
0 2026-01-18             7
1 2026-01-19             5
2 2026-01-20             5
3 2026-01-21             5
4 2026-01-22            16

(113, 2)

In [4]:
ig_views = pd.read_csv("../Data/ig_views.csv", encoding="utf-16", skiprows=2)

ig_views["Date"] = pd.to_datetime(ig_views["Date"])
ig_views = ig_views.rename(columns={"Primary": "IG_Views"})

display(ig_views.head())
print(ig_views.shape)

        Date  IG_Views
0 2026-01-01       229
1 2026-01-02        90
2 2026-01-03      1504
3 2026-01-04     19621
4 2026-01-05     16045

(169, 2)

In [5]:
master = pd.merge(
    traffic,
    ig_views,
    on="Date",
    how="left"
)

display(master.head())
print(master.shape)

        Date  Active_Users  IG_Views
0 2026-01-18             7        32
1 2026-01-19             5       966
2 2026-01-20             5       299
3 2026-01-21             5       451
4 2026-01-22            16        58

(113, 3)

In [6]:
print("IG Views min date:", ig_views["Date"].min())
print("IG Views max date:", ig_views["Date"].max())

print("Traffic min date:", traffic["Date"].min())
print("Traffic max date:", traffic["Date"].max())

IG Views min date: 2026-01-01 00:00:00
IG Views max date: 2026-06-18 00:00:00
Traffic min date: 2026-01-18 00:00:00
Traffic max date: 2026-06-17 00:00:00

In [7]:
print(master.isna().sum())
display(master.head(10))
display(master.tail(10))

Date            0
Active_Users    0
IG_Views        0
dtype: int64

        Date  Active_Users  IG_Views
0 2026-01-18             7        32
1 2026-01-19             5       966
2 2026-01-20             5       299
3 2026-01-21             5       451
4 2026-01-22            16        58
5 2026-01-23             7       125
6 2026-01-24             2        20
7 2026-01-25             3        44
8 2026-01-26            36         8
9 2026-01-27            14        10

          Date  Active_Users  IG_Views
103 2026-06-05             1         1
104 2026-06-06             1         0
105 2026-06-07             4         0
106 2026-06-08             3        89
107 2026-06-10             1         9
108 2026-06-11             1         0
109 2026-06-13             3         0
110 2026-06-15             3         0
111 2026-06-16             2         1
112 2026-06-17             1         6

In [8]:
matching_dates = traffic["Date"].isin(ig_views["Date"]).sum()

print("Traffic rows:", len(traffic))
print("Matching dates with IG views:", matching_dates)

Traffic rows: 113
Matching dates with IG views: 113

In [9]:
def load_meta_file(filename, new_column_name):
    df = pd.read_csv(
        f"../Data/{filename}",
        encoding="utf-16",
        skiprows=2
    )
    df["Date"] = pd.to_datetime(df["Date"])
    df = df.rename(columns={"Primary": new_column_name})
    return df[["Date", new_column_name]]

In [10]:
ig_interactions = load_meta_file("ig_interactions.csv", "IG_Interactions")
ig_clicks = load_meta_file("ig_link clicks.csv", "IG_Link_Clicks")
ig_visits = load_meta_file("ig_profile_visits.csv", "IG_Profile_Visits")
ig_follows = load_meta_file("ig_follows.csv", "IG_Follows")

fb_views = load_meta_file("fb_views.csv", "FB_Views")
fb_interactions = load_meta_file("fb_interactions.csv", "FB_Interactions")
fb_clicks = load_meta_file("fb_link clicks.csv", "FB_Link_Clicks")
fb_visits = load_meta_file("fb_visits.csv", "FB_Visits")
fb_follows = load_meta_file("fb_follows.csv", "FB_Follows")

In [11]:
master = traffic.copy()

for df in [
    ig_views,
    ig_interactions,
    ig_clicks,
    ig_visits,
    ig_follows,
    fb_views,
    fb_interactions,
    fb_clicks,
    fb_visits,
    fb_follows
]:
    master = pd.merge(master, df, on="Date", how="left")

master = master.fillna(0)

display(master.head())
print(master.shape)
print(master.isna().sum())

,Date,Active_Users,IG_Views,IG_Interactions,IG_Link_Clicks,IG_Profile_Visits,IG_Follows,FB_Views,FB_Interactions,FB_Link_Clicks,FB_Visits,FB_Follows
0,2026-01-18,7,32,2,0,19,1.0,66,2,1,13,0
1,2026-01-19,5,966,83,0,55,5.0,82,6,0,4,0
2,2026-01-20,5,299,3,0,24,4.0,2,0,0,1,0
3,2026-01-21,5,451,40,0,8,1.0,64,2,0,10,0
4,2026-01-22,16,58,4,0,14,3.0,13,0,0,5,0

(113, 12)
Date                 0
Active_Users         0
IG_Views             0
IG_Interactions      0
IG_Link_Clicks       0
IG_Profile_Visits    0
IG_Follows           0
FB_Views             0
FB_Interactions      0
FB_Link_Clicks       0
FB_Visits            0
FB_Follows           0
dtype: int64

In [12]:
master["DayOfWeek"] = master["Date"].dt.dayofweek
master["Month"] = master["Date"].dt.month
master["Quarter"] = master["Date"].dt.quarter
master["Weekend"] = (master["DayOfWeek"] >= 5).astype(int)

display(master.head())
print(master.shape)

,Date,Active_Users,IG_Views,IG_Interactions,IG_Link_Clicks,IG_Profile_Visits,IG_Follows,FB_Views,FB_Interactions,FB_Link_Clicks,FB_Visits,FB_Follows,DayOfWeek,Month,Quarter,Weekend
0,2026-01-18,7,32,2,0,19,1.0,66,2,1,13,0,6,1,1,1
1,2026-01-19,5,966,83,0,55,5.0,82,6,0,4,0,0,1,1,0
2,2026-01-20,5,299,3,0,24,4.0,2,0,0,1,0,1,1,1,0
3,2026-01-21,5,451,40,0,8,1.0,64,2,0,10,0,2,1,1,0
4,2026-01-22,16,58,4,0,14,3.0,13,0,0,5,0,3,1,1,0

(113, 16)

In [13]:
X = master[[
    "IG_Views",
    "IG_Interactions",
    "IG_Link_Clicks",
    "IG_Profile_Visits",
    "IG_Follows",
    "FB_Views",
    "FB_Interactions",
    "FB_Link_Clicks",
    "FB_Visits",
    "FB_Follows",
    "DayOfWeek",
    "Month",
    "Quarter",
    "Weekend"
]]

y = master["Active_Users"]

print(X.shape)
print(y.shape)

(113, 14)
(113,)

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

mlr = LinearRegression()

mlr.fit(X, y)

mlr_pred = mlr.predict(X)

mlr_r2 = r2_score(y, mlr_pred)

print("MLR R²:", round(mlr_r2,4))

MLR R²: 0.1619

In [15]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X, y)

rf_pred = rf.predict(X)

rf_r2 = r2_score(y, rf_pred)

print("RF R²:", round(rf_r2,4))

RF R²: 0.8709

In [16]:
top_delta = master.sort_values(
    "Abs_Delta",
    ascending=False
)

display(
    top_delta[
        ["Date",
         "Active_Users",
         "Delta",
         "Abs_Delta"]
    ].head(10)
)

KeyError: 'Abs_Delta'

In [17]:
master["Predicted_MLR"] = mlr_pred
master["Predicted_RF"] = rf_pred

master["Delta"] = (
    master["Predicted_RF"]
    - master["Predicted_MLR"]
)

master["Abs_Delta"] = abs(master["Delta"])

In [18]:
print(master.columns)

Index(['Date', 'Active_Users', 'IG_Views', 'IG_Interactions', 'IG_Link_Clicks',
       'IG_Profile_Visits', 'IG_Follows', 'FB_Views', 'FB_Interactions',
       'FB_Link_Clicks', 'FB_Visits', 'FB_Follows', 'DayOfWeek', 'Month',
       'Quarter', 'Weekend', 'Predicted_MLR', 'Predicted_RF', 'Delta',
       'Abs_Delta'],
      dtype='object')

In [19]:
top_delta = master.sort_values(
    by="Abs_Delta",
    ascending=False
)

display(
    top_delta[
        [
            "Date",
            "Active_Users",
            "Predicted_MLR",
            "Predicted_RF",
            "Delta",
            "Abs_Delta"
        ]
    ].head(10)
)

,Date,Active_Users,Predicted_MLR,Predicted_RF,Delta,Abs_Delta
8,2026-01-26,36,7.225829,25.945,18.719171,18.719171
53,2026-03-28,15,2.654859,10.540,7.885141,7.885141
9,2026-01-27,14,6.786657,14.310,7.523343,7.523343
4,2026-01-22,16,5.642915,12.180,6.537085,6.537085
88,2026-05-15,6,0.978953,4.855,3.876047,3.876047
98,2026-05-29,5,0.273590,4.025,3.751410,3.751410
10,2026-01-28,11,5.629268,9.195,3.565732,3.565732
105,2026-06-07,4,-0.079962,3.250,3.329962,3.329962
87,2026-05-14,7,1.621218,4.875,3.253782,3.253782
90,2026-05-17,4,1.173897,4.150,2.976103,2.976103

In [20]:
print("MLR R² =", round(mlr_r2,4))
print("RF R² =", round(rf_r2,4))

print("\nMaximum Delta:")
print(master["Abs_Delta"].max())

MLR R² = 0.1619
RF R² = 0.8709

Maximum Delta:
18.719170758284164

In [21]:
equation = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": mlr.coef_
})

print("Intercept:", mlr.intercept_)
display(equation)

Intercept: 6.677414812660391

              Feature   Coefficient
0            IG_Views -5.476905e-03
1     IG_Interactions -3.950524e-02
2      IG_Link_Clicks  8.867906e-15
3   IG_Profile_Visits  1.247325e-01
4          IG_Follows -2.901921e-01
5            FB_Views  5.240005e-02
6     FB_Interactions -9.943804e-02
7      FB_Link_Clicks -1.500828e+00
8           FB_Visits -8.868796e-02
9          FB_Follows -6.661338e-16
10          DayOfWeek -6.301779e-01
11              Month -1.216757e+00
12            Quarter  1.435032e+00
13            Weekend  1.454167e+00

In [22]:
equation = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": mlr.coef_
})

print("Intercept:", mlr.intercept_)
display(equation)

Intercept: 6.677414812660391

              Feature   Coefficient
0            IG_Views -5.476905e-03
1     IG_Interactions -3.950524e-02
2      IG_Link_Clicks  8.867906e-15
3   IG_Profile_Visits  1.247325e-01
4          IG_Follows -2.901921e-01
5            FB_Views  5.240005e-02
6     FB_Interactions -9.943804e-02
7      FB_Link_Clicks -1.500828e+00
8           FB_Visits -8.868796e-02
9          FB_Follows -6.661338e-16
10          DayOfWeek -6.301779e-01
11              Month -1.216757e+00
12            Quarter  1.435032e+00
13            Weekend  1.454167e+00

In [23]:
equation = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": mlr.coef_
})

print("Intercept:", mlr.intercept_)
display(equation)

Intercept: 6.677414812660391

              Feature   Coefficient
0            IG_Views -5.476905e-03
1     IG_Interactions -3.950524e-02
2      IG_Link_Clicks  8.867906e-15
3   IG_Profile_Visits  1.247325e-01
4          IG_Follows -2.901921e-01
5            FB_Views  5.240005e-02
6     FB_Interactions -9.943804e-02
7      FB_Link_Clicks -1.500828e+00
8           FB_Visits -8.868796e-02
9          FB_Follows -6.661338e-16
10          DayOfWeek -6.301779e-01
11              Month -1.216757e+00
12            Quarter  1.435032e+00
13            Weekend  1.454167e+00

In [24]:
equation.to_excel(
    "../Outputs/MLR_Coefficients.xlsx",
    index=False
)

print("Excel file saved!")

Excel file saved!

In [25]:
equation

              Feature   Coefficient
0            IG_Views -5.476905e-03
1     IG_Interactions -3.950524e-02
2      IG_Link_Clicks  8.867906e-15
3   IG_Profile_Visits  1.247325e-01
4          IG_Follows -2.901921e-01
5            FB_Views  5.240005e-02
6     FB_Interactions -9.943804e-02
7      FB_Link_Clicks -1.500828e+00
8           FB_Visits -8.868796e-02
9          FB_Follows -6.661338e-16
10          DayOfWeek -6.301779e-01
11              Month -1.216757e+00
12            Quarter  1.435032e+00
13            Weekend  1.454167e+00

In [26]:
master.to_excel(
    "../Outputs/OFKA_Master_Dataset.xlsx",
    index=False
)

print("Master dataset exported")

Master dataset exported

In [27]:
delta_report = master[
    [
        "Date",
        "Active_Users",
        "Predicted_MLR",
        "Predicted_RF",
        "Delta",
        "Abs_Delta"
    ]
]

delta_report.to_excel(
    "../Outputs/OFKA_Delta_Report.xlsx",
    index=False
)

print("Delta report exported")

Delta report exported

In [28]:
top_delta = master.sort_values(
    by="Abs_Delta",
    ascending=False
)

top10 = top_delta[
    [
        "Date",
        "Active_Users",
        "Predicted_MLR",
        "Predicted_RF",
        "Delta",
        "Abs_Delta"
    ]
].head(10)

top10.to_excel(
    "../Outputs/OFKA_Top10_Tipping_Points.xlsx",
    index=False
)

display(top10)

,Date,Active_Users,Predicted_MLR,Predicted_RF,Delta,Abs_Delta
8,2026-01-26,36,7.225829,25.945,18.719171,18.719171
53,2026-03-28,15,2.654859,10.540,7.885141,7.885141
9,2026-01-27,14,6.786657,14.310,7.523343,7.523343
4,2026-01-22,16,5.642915,12.180,6.537085,6.537085
88,2026-05-15,6,0.978953,4.855,3.876047,3.876047
98,2026-05-29,5,0.273590,4.025,3.751410,3.751410
10,2026-01-28,11,5.629268,9.195,3.565732,3.565732
105,2026-06-07,4,-0.079962,3.250,3.329962,3.329962
87,2026-05-14,7,1.621218,4.875,3.253782,3.253782
90,2026-05-17,4,1.173897,4.150,2.976103,2.976103

In [29]:
top_delta[
[
"Date",
"Active_Users",
"IG_Views",
"IG_Interactions",
"IG_Profile_Visits",
"IG_Follows",
"FB_Views",
"FB_Interactions",
"FB_Link_Clicks",
"FB_Visits",
"Weekend",
"Month",
"Quarter",
"Predicted_MLR",
"Predicted_RF",
"Delta"
]
].head(4)

,Date,Active_Users,IG_Views,IG_Interactions,IG_Profile_Visits,IG_Follows,FB_Views,FB_Interactions,FB_Link_Clicks,FB_Visits,Weekend,Month,Quarter,Predicted_MLR,Predicted_RF,Delta
8,2026-01-26,36,8,0,4,0.0,1,0,0,2,0,1,1,7.225829,25.945,18.719171
53,2026-03-28,15,4,0,0,0.0,0,0,0,1,1,3,1,2.654859,10.540,7.885141
9,2026-01-27,14,10,0,2,0.0,13,0,0,4,0,1,1,6.786657,14.310,7.523343
4,2026-01-22,16,58,4,14,3.0,13,0,0,5,0,1,1,5.642915,12.180,6.537085